### ISSUE TITLE
po/fr.po generates warning

### ISSUE THREAD

**Issue by quozl** [sugarlabs/jukebox-activity#12]
```
$ python setup.py dist_xo
WARNING:root:Translation of summary on file po/fr.po have \n chars. Should be removed
```

@leonardcj, this is as obvious as it looks, right?  Just checking, I'm not sure.

**Comment by leonardcj** [comment]
I think so.  I haven't seen newlines mismatch cause a fatal error before, but I just deleted the newlines on Pootle.  From the new version release notice I saw, I'm assuming you fixed it locally.  Please let me know if I need to re-commit the updated PO from Poolte to fix the repo version, and I will.

**Comment by quozl** [comment]
Thanks.  No, it wasn't fixed in v33, as it didn't block release.  Fixed in https://github.com/sugarlabs/jukebox-activity/commit/dada68509a5fecc03c21f3693de6af93c52c4808 .
