### ISSUE TITLE
Enable visualisations in the playbin element for audio content

### ISSUE THREAD

**Issue by quozl** [sugarlabs/jukebox-activity#23]
GStreamer has a playbin element.  One of the element properties is flags.  One of the bits in flags is "Render visualisation when no video is present".  When enabled, visualisations are shown, but they are in a separate window.  They should be in the main window of the activity.

**Comment by avinashbharti97** [comment]
By 'Enable Visualisations' Do you mean showing artwork that comes with audio file or if not available then any animation related to music playing(something like attached gif)?

![t8x9](https://user-images.githubusercontent.com/22724583/51747230-daefa100-20ce-11e9-9117-8ea5de68bf62.gif)

**Comment by quozl** [comment]
Issue edited, thanks.

**Comment by nswarup14** [comment]
I enabled the line that was commented out in the activity and tested on Sugar 0.114.

When I ran an audio file, no visualisations were present. However when I ran an audio file after playing a video file, the visualisations were present for a very very brief duration and then disappeared. 

I have attached a screenshot for your reference.
![IMG_20190810_130029](https://user-images.githubusercontent.com/34597895/62819253-34518600-bb70-11e9-98e8-e834b9711572.jpg)

**Comment by quozl** [comment]
I see that too, with Ubuntu 18.04.  Probably an improvement in the GStreamer package since September.  We may have to find the problem in GStreamer source code or make a standalone GTK reproducer to log a bug with GStreamer.

**Comment by nswarup14** [comment]
@quozl 
Thanks.

I shall try to create a minimal reproducer based on the code from the activity, and try to enable visualisations there. I shall report my findings here.

**Comment by quozl** [comment]
Backported for Python 2 as Jukebox 34.1
