### ISSUE TITLE
OpenGL renderer window crashes

### ISSUE THREAD

**Issue by sanjaymaniam** [sugarlabs/jukebox-activity#28]
Moving the OpenGL renderer window leaves a trail behind it. The renderer opens up as a separate activity instead of being integrated with Jukebox. The right side of the activity is "transparent". When I switch to Jukebox from another activity, it retains the view from the previous screen.

The log says:
```
** (sugar-activity3:29213): CRITICAL **: 02:20:10.157: gst_gl_window_draw: assertion 'GST_IS_GL_WINDOW (window)' failed

(sugar-activity3:29213): GStreamer-CRITICAL **: 02:20:10.157: gst_object_unref: assertion '((GObject *) object)->ref_count > 0' failed
```
I'm running Sugar 0.116 (on Debian Buster), on a VirtualBox.

**Comment by sanjaymaniam** [comment]
@srevinsaju This might interest you, since pull request #27 addressed this :)

**Comment by quozl** [comment]
What version of Jukebox?  On latest v36 I'm unable to move the window because it has embedded into the activity canvas.

**Comment by sanjaymaniam** [comment]
@quozl Sorry, should've mentioned it earlier. I'm running v36, cloned from this repo. 

There's also this in the logs for me now:
```
(sugar-activity3:14422): dbind-WARNING **: 01:17:44.527: Couldn't register with accessibility bus:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the
message bus security policy blocked the reply, the reply timeout expired, or the network 
connection was broken.
```

**Comment by quozl** [comment]
@sanjay237, thanks, indeed it does what you say on Debian Buster in a VM.

@srevinsaju, you fixed this, any ideas why it is not working?

My guess is that either;
* the version of GStreamer or GTK has to change, or;
* this is a _race condition_ that is best exposed by a VM.

For the former, upgrading to Debian Bullseye (aka testing) is the step to try.  Debian Buster has GStreamer 1.14.4 and GTK 3.24.5.  @srevinsaju, what versions are you using?

For the latter, I've seen similar race conditions while developing the Record activity, which also uses a GStreamer embedded window.  I had to read GStreamer documentation for the supported recipes for embedding and make sure Record used them.  I've not checked if Jukebox uses the recipes properly.

**Comment by srevinsaju** [comment]
I will check it now

**Comment by srevinsaju** [comment]
The versions I have used:
* Gtk 3.24.13
* Gst 1.0
* GstVideo 1.0
* GObject 2.0
* Gdk 3.0
* Gio 2.0

Tested right now, I had the same error when I uncommented the changes made before I made thechange, it created a separate new window. A new window was represented by a `O` in the title bar. If a new window was created, it shuld have shown that `O` again on the titlebar, but corresponding to my versions, it didn't. @sanjay237 could you please confirm the versions and also check the latest commit is what you have tested?

![image](https://user-images.githubusercontent.com/48695438/74064218-428b3c80-4a03-11ea-8401-3c25ac7bea1c.png)
![image](https://user-images.githubusercontent.com/48695438/74064271-5fc00b00-4a03-11ea-8f57-0451f9f976e8.png)
Notice the frame, to see if the `O` exists.

**Comment by quozl** [comment]
> The versions I have used:
>     * Gtk 3.24.13

Thanks.

>     * Gst 1.0
>     * GstVideo 1.0
>     * GObject 2.0
>     * Gdk 3.0
>     * Gio 2.0

They are API versions, not software package release versions.  Please check for the release version of GStreamer?

**Comment by srevinsaju** [comment]
Ohk @quozl :man_facepalming: 
* Gst 1.16.2

**Comment by quozl** [comment]
Okay, very different.  Therefore not comparable result.

**Comment by srevinsaju** [comment]
Maybe thats the reason it didn't work previously too. Thanks :)

**Comment by sanjaymaniam** [comment]
Ah, I'm on GStreamer 1.14.4. @srevinsaju Did you upgrade from the default?

**Comment by srevinsaju** [comment]
@sanjay237, no clue, I package sugar for Arch Linux, so I possibly might have used the latest releases,

**Comment by sanjaymaniam** [comment]
@srevinsaju Also, do _any_ of these show up in your log files?

```
(sugar-activity3:14422): dbind-WARNING **: 01:17:44.527: Couldn't register with accessibility bus:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the
message bus security policy blocked the reply, the reply timeout expired, or the network 
connection was broken.

** (sugar-activity3:29213): CRITICAL **: 02:20:10.157: gst_gl_window_draw: assertion 'GST_IS_GL_WINDOW (window)' failed

(sugar-activity3:29213): GStreamer-CRITICAL **: 02:20:10.157: gst_object_unref: assertion '((GObject *) object)->ref_count > 0' failed

```

**Comment by srevinsaju** [comment]
No, I dont have any errors in the log, maybe some other component might be outdated

**Comment by sanjay237** [comment]
@quozl Since you reproduced the bug, can you tell me if this user-end hack works on your setup?

- Run Jukebox and play an audio file.
- A movable and trail leaving OpenGL Renderer window pops up, close it.
- Jukebox says `Error: This "application/octet-stream" file can't be played` on the screen. Close it too.
- Now play the audio file again.

**Comment by sanjaymaniam** [comment]
I upgraded to Debian Bullseye. With Gtk 3.24.11-2 and Gst 1.16.2-2, the issue still persists. So it's not a problem of wrong dependency versions.

Also, the previous errors are now replaced with:

```
1581189528.074764 ERROR root: ERROR MESSAGE: gst-resource-error-quark: Quit requested (3)
1581189528.075037 ERROR root: ERROR DETAIL: gstglimagesink.c(1781): gst_glimage_sink_show_frame (): /GstPipeline:pipeline0/GstPlayBin:playbin0/GstPlaySink:playsink
/GstBin:vbin/GstAutoVideoSink:videosink/GstGLImageSinkBin:videosink-actual-sink-glimage/GstGLImageSink:sink
```

But for the Record activity, which works okay, I get _one_ of the older errors:
`(sugar-activity3:27672): GStreamer-CRITICAL **: 00:43:24.245: gst_object_unref: assertion '((GObject *) object)->ref_count > 0' failed`

I'm hazy on what direction to head in next, could use a pointer @srevinsaju @quozl

**Comment by srevinsaju** [comment]
@sanjay237 Are you testing it on a VM?
I would like to have more information 
* A copy of your `neofetch`
* Your OpenGL number, (possibly because of an older hardware)
Thanks

**Comment by sanjaymaniam** [comment]
Here you go:

```
sanjay@debian:~$ neofetch

       _,met$$$$$gg.          sanjay@debian 
    ,g$$$$$$$$$$$$$$$P.       ------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux bullseye/sid x86_64 
 ,$$P'              `$$$.     Host: VirtualBox 1.2 
',$$P       ,ggs.     `$$b:   Kernel: 4.19.0-6-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 3 hours, 41 mins 
 $$P      d$'     ,    $$P    Packages: 1483 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.0.11 
 $$;      Y$b._   _,d$P'      Resolution: 1600x737 
 Y$$.    `.`"Y$$$$P"'         DE: lightdm-xsession 
 `$$b      "-.__              WM: Metacity 
  `Y$$                        Theme: sugar-72 [GTK2], Adwaita [GTK3] 
   `Y$$.                      Icons: sugar [GTK2], Adwaita [GTK3] 
     `$$b.                    Terminal: T 
       `Y$$b.                 CPU: Intel i5-7200U (1) @ 2.711GHz 
          `"Y$b._             GPU: 00:02.0 VMware SVGA II Adapter 
              `"""            Memory: 422MiB / 987MiB 
```

**Comment by srevinsaju** [comment]
Hmm ok, @sanjay237 can you test it on a native device and confirm the error recreates?

**Comment by sanjaymaniam** [comment]
Sure, sure, I'll have to build it from source right?

**Comment by srevinsaju** [comment]
Which OS are you running natively?

**Comment by sanjaymaniam** [comment]
Ubuntu 18.04

**Comment by srevinsaju** [comment]
Yea, you would have to build from source.

**Comment by sanjay237** [comment]
> But for the Record activity, which works okay, I get _one_ of the older errors:
> `(sugar-activity3:27672): GStreamer-CRITICAL **: 00:43:24.245: gst_object_unref: assertion '((GObject *) object)->ref_count > 0' failed`

@srevinsaju Can you reproduce this on Record?

**Comment by sanjaymaniam** [comment]
> But for the Record activity, which works okay, I get _one_ of the older errors:
> `(sugar-activity3:27672): GStreamer-CRITICAL **: 00:43:24.245: gst_object_unref: assertion '((GObject *) object)->ref_count > 0' failed`

@srevinsaju Can you reproduce this on Record?

**Comment by srevinsaju** [comment]
I will test

**Comment by srevinsaju** [comment]
@sanjay237 how did you get that error? I can do basic activities with record
Like, which option triggered that error?

**Comment by sanjaymaniam** [comment]
All I did was open, record a file, play it, and then close.

**Comment by srevinsaju** [comment]
No, I have no errors as given above, maybe a faulty installation. Trying it again on the native build will probably help out

**Comment by srevinsaju** [comment]
@sanjay237 do you have `ncurses-dev` installed on your debian?

**Comment by srevinsaju** [comment]
@sanjay237 seems like your error have been seen by a few others, maybe you are running your VirtualBox with too less ram or with no swap block, so the cache is fully limited.

From Gstreamer release notes:
![image](https://user-images.githubusercontent.com/48695438/74091604-53eb4c00-4aca-11ea-8125-c5d361b3dcb1.png)

Hopefully, by creating a swap drive, and by increasing you RAM to something like 2048 MB should do the thing. If you use VirtualBox, try using `VBoxSVGA` and not `VMSVGA` as I had some problem playing a video on a Ubuntu 20.04 Focal Fossa (unrelated to sugar), but might have a common relation

Alternatively, it seems a bug long time ago in Debian once upon a time fixed. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=475735
As the OP says, it might be  because of an older `Gio` or `gvfs`, so please see your gvfs version too, and check if its the latest.

Hope it helps

**Comment by srevinsaju** [comment]
@sanjay237 I was able to reproduce the error with Record Activity, your same error code's come up,
But, we can fix that error by:
* Add 3D acceleration to Graphics tab (Vbox)
* Increase RAM to 2048 MB
* Increase Video Memory from 16MB to 128 MB.

**Comment by sanjaymaniam** [comment]
> @sanjay237 do you have `ncurses-dev` installed on your debian?

I didn't, installed now. Issue persists..

> @sanjay237 I was able to reproduce the error with Record Activity, your same error code's come up,
> But, we can fix that error by:
> 
>     * Add 3D acceleration to Graphics tab (Vbox)
> 
>     * Increase RAM to 2048 MB
> 
>     * Increase Video Memory from 16MB to 128 MB.

Yes, @srevinsaju , that fixes it :)

**Comment by srevinsaju** [comment]
Great to know it worked!

**Comment by sanjaymaniam** [comment]
You want to add that to the documentation somewhere? Other things equal, it was 3D acceleration that made the difference :)

**Comment by sanjaymaniam** [comment]
And though it works as expected, these error logs still show up:

```
1581225309.980518 ERROR root: ERROR MESSAGE: gst-resource-error-quark: Quit requested (3)
1581225309.980701 ERROR root: ERROR DETAIL: gstglimagesink.c(1781): gst_glimage_sink_show_frame (): /GstPipeline:pipeline0/GstPlayBin:playbin0/GstPlaySink:playsink/GstBin:vbin/GstAutoVideoSink:videosink/GstGLImageSinkBin:videosink-actual-sink-glimage/GstGLImageSink:sink
Normal successful completion, pid 1765 activity_id 96b822a7df30f12e06033a39b7b25c5bda9452cd
```

**Comment by srevinsaju** [comment]
that is a broken installation of the gstreamer, probably a reinstall or clean build should fix the issue.

**Comment by sanjaymaniam** [comment]
Alright, will try that!

**Comment by quozl** [comment]
Thanks for investigating.  So to summarise, the problem happened because the virtual machines we have been using did not support OpenGL, which caused MESA to render using the CPU, and the delay somehow induced a race condition with GTK and GStreamer's reparenting of the window.  I'm not surprised.

Behaviour in a virtual machine isn't really a problem that needs deep investigation; we're intending Sugar run on real hardware, not in a virtual machine.  We don't document setup on a virtual machine, so no need to change documentation.

**Comment by sanjaymaniam** [comment]
Thanks for putting it together, quozl.
