### ISSUE TITLE
Jukebox isn't added to favorites by default

### ISSUE THREAD

**Issue by sanjaymaniam** [sugarlabs/jukebox-activity#29]
Hi, the other activities show up in the favorites view automatically, but jukebox doesn't. I'm not sure if this was intended and I'm nitpicking, but anyways :)

This is when I'm running Sugar 0.116 (Debian Buster) on a VM.

**Comment by sanjaymaniam** [comment]
Note: This problem solved itself when I upgraded to Debian Bullseye.

**Comment by quozl** [comment]
Thanks.  That's expected behaviour, and won't be fixed.  Jukebox and a list of other activities are not meant to show in favourites unless the user asks for them to be shown.

https://github.com/sugarlabs/sugar/blob/master/data/activities.hidden contains the complete list.
