### ISSUE TITLE
Jukebox activity: Gtk-CRITICAL: gtk_toolbar_remove: assertion 'content_to_remove != NULL' failed

### ISSUE THREAD

**Issue by aperezbios** [sugarlabs/jukebox-activity#32]
With Jukebox 36, and the latest version of Sugar (0.118), upon launch of the Jukebox activity, the following is logged:

```
(sugar-activity3:3753): Gtk-CRITICAL **: 16:45:26.530: gtk_toolbar_remove: assertion 'content_to_remove != NULL' failed

(sugar-activity3:3753): Gtk-CRITICAL **: 16:46:52.733: gtk_toolbar_remove: assertion 'content_to_remove != NULL' failed
```

**Comment by srevinsaju** [comment]
Tested, on Arch Linux Sugar 0.118, cant reproduce both on https://github.com/sugarlabs/jukebox-activity/tree/v36 as well as on `master` as of https://github.com/sugarlabs/jukebox-activity/commit/e11f40c94c1c6302d3e36ddf4dc8101732ffb9d9

What I tested:
* Start Sugar
* Open Jukebox

No errors, warnings in logs.

**Comment by Dimi20cen** [comment]
I get the issue when I resize the activity, tested on sugar 0.117
